This sheet contains some random code that I used for experimentation and may want to review later on.

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [6]:
layer = keras.layers.Dense(3)
layer.build((None, 3))  # Create the weights

print("weights:", len(layer.weights))
print("trainable_weights:", len(layer.trainable_weights))
print("non_trainable_weights:", len(layer.non_trainable_weights))

weights: 2
trainable_weights: 2
non_trainable_weights: 0


In [14]:
layer.set_weights([np.eye(3,3), np.zeros(3)])
layer.weights

[<tf.Variable 'kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [18]:
model = keras.Sequential()
model.add(layer)

In [20]:
model.predict([[0, 1, 0]])

array([[0., 1., 0.]], dtype=float32)

In [21]:
layer.set_weights([np.eye(3,3), np.ones(3)])
layer.weights

[<tf.Variable 'kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>]

In [22]:
model.predict([[0, 1, 0]])

array([[1., 2., 1.]], dtype=float32)